# Generated by Django 4.0 on 2023-07-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('car_info', models.CharField(max_length=100)),
                ('register', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail/images')),
                ('engine_type', models.CharField(max_length=50)),
                ('engine_capacity', models.CharField(max_length=100)),
                ('assembly', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=100)),
                ('secondary_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.useraccount')),
            ],
        ),
    ]
