# Generated by Django 4.0 on 2023-08-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPrice',
        ),
    ]
